import { deflateSync } from 'node:zlib';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { BRAND, ICON_SIZES, ICON_SVG, iconBitmap } from './brand.mjs';

const table=[];
for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}
const crc=buffer=>{let c=0xffffffff;for(const b of buffer)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
function chunk(type,data){const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(size) {
  const bitmap=iconBitmap(size), raw=Buffer.alloc((size*4+1)*size);
  for(let y=0;y<size;y++) bitmap.copy(raw,y*(size*4+1)+1,y*size*4,(y+1)*size*4);
  const header=Buffer.alloc(13);header.writeUInt32BE(size);header.writeUInt32BE(size,4);header[8]=8;header[9]=6;
  return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);
}
const images=ICON_SIZES.map(png), header=Buffer.alloc(6+16*images.length);
header.writeUInt16LE(1,2);header.writeUInt16LE(images.length,4);
let offset=header.length;
for(let n=0;n<images.length;n++) {
  const i=6+n*16,size=ICON_SIZES[n];header[i]=header[i+1]=size===256?0:size;
  header.writeUInt16LE(1,i+4);header.writeUInt16LE(32,i+6);header.writeUInt32LE(images[n].length,i+8);header.writeUInt32LE(offset,i+12);offset+=images[n].length;
}
const save=(path,data)=>writeFile(fileURLToPath(new URL('../'+path,import.meta.url)),data);
await save('desktop/icon.png',images.at(-1));
await save('desktop/tray.png',images[ICON_SIZES.indexOf(32)]);
await save('desktop/icon.ico',Buffer.concat([header,...images]));
await save('public/brand-icon.svg',ICON_SVG+'\n');
await save('public/brand.css',`/* Generated by npm run brand:icons. */
:root { --brand-white:${BRAND.white}; --brand-green:${BRAND.green}; --brand-ink:${BRAND.ink}; --brand-soft:#f2ffd6; background:var(--brand-white); }
.brand-mark { background:transparent url('/brand-icon.svg') center / contain no-repeat; font-size:0; }
.brand-mark>span { display:none; }
.nav-item.active { background:var(--brand-soft); color:var(--brand-ink); }
.nav-item.active:before,.switch.on,.mode-dot:not(.demo),.tiny-dot:not(.blue-bg):not(.orange-bg),.journal-track b { background:var(--brand-green); }
.switch.on>span { box-shadow:0 0 0 1px #20251b40; }
.companion-note,.privacy-card { background:var(--brand-soft); }
.companion-glyph { color:#487000; }
button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,[tabindex]:focus-visible { outline-color:#487000; }
`);
console.log('Generated white/neon-green app, tray, favicon and theme assets.');
