"""Measure alpha frames without changing any generated image pixels."""
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
art_root = root / 'public' / 'artwork'
prompts = json.loads((art_root / 'generation-prompts.json').read_text(encoding='utf-8'))['prompts']
tables = {'cities': {}, 'fleet': {}, 'props': {}}
props = {'crew', 'crane', 'airdrop'}

def measure(path, count):
    with Image.open(path) as im:
        assert im.mode == 'RGBA', f'{path} must retain alpha'
        width, height = im.size
        alpha = im.getchannel('A').point(lambda value: 255 if value > 32 else 0)
        columns = alpha.getprojection()[0]
        cuts = [0]
        # Uneven spacing needs a genuinely clear divider, not equal thirds.
        for i in range(1, count):
            nominal = round(i * width / count)
            radius = round(width / count * .12)
            gaps = [x for x in range(nominal-radius, nominal+radius+1) if not columns[x]]
            assert gaps, f'{path}: overlapping subjects near frame {i}'
            cuts.append(min(gaps, key=lambda x: abs(x-nominal)))
        cuts.append(width)
        frames = []
        for i in range(count):
            left, right = cuts[i], cuts[i+1]
            box = alpha.crop((left, 0, right, height)).getbbox()
            assert box, f'{path} frame {i} is empty'
            x, y, end_x, end_y = box
            frames.append([x + left, y, end_x - x, end_y - y])
        return {'size': [width, height], 'frames': frames}

for spec in prompts:
    ident, kind = spec['id'], spec['kind']
    if ident.endswith('-empty'):
        continue
    path = art_root / kind / (ident + '.png')
    if not path.exists():
        continue
    table = tables['props' if ident in props else kind]
    table[ident] = measure(path, 3 if kind == 'fleet' and ident not in {'crane', 'airdrop'} else 1)
    empty_path = path.with_name(ident + '-empty.png')
    if empty_path.exists():
        art = table[ident]
        empty = measure(empty_path, len(art['frames']))
        for i, (a, b) in enumerate(zip(art['frames'], empty['frames'])):
            sa, sb = art['size'], empty['size']
            x = min(a[0]/sa[0], b[0]/sb[0])
            y = min(a[1]/sa[1], b[1]/sb[1])
            right = max((a[0]+a[2])/sa[0], (b[0]+b[2])/sb[0])
            bottom = max((a[1]+a[3])/sa[1], (b[1]+b[3])/sb[1])
            for obj in (art, empty):
                w, h = obj['size']
                obj['frames'][i] = [round(value, 6) for value in [x*w, y*h, (right-x)*w, (bottom-y)*h]]
        art['empty'] = empty

lines = ['// Measured alpha bounds; generated by scripts/measure-artwork.py.']
for name, table in [('CITY_ART', tables['cities']), ('FLEET_ART', tables['fleet']), ('PROP_ART', tables['props'])]:
    lines.append('export const ' + name + '=' + json.dumps(table, separators=(',', ':')) + ';')
lines.append("export const ILLUSTRATION_ASSETS=[...Object.keys(CITY_ART).map(id=>'artwork/cities/'+id+'.png'),...Object.entries(FLEET_ART).flatMap(([id,art])=>['artwork/fleet/'+id+'.png',...(art.empty?['artwork/fleet/'+id+'-empty.png']:[])]),...Object.keys(PROP_ART).map(id=>'artwork/fleet/'+id+'.png')];")
(art_root / 'manifest.js').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(json.dumps({key: len(value) for key, value in tables.items()}))
